mathbreakers/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

import mathbreakers.views
import mathbreakers.userviews
import mathbreakers.ajax
import mathbreakers.client
import mathbreakers.bugs
import mathbreakers.commoncore
import mathbreakers.purchase
import mathbreakers.classroom
import mathbreakers.su
import mathbreakers.preorder
import mathbreakers.analytics
import mathbreakers.survey
import mathbreakers.session
import mathbreakers.modifydb
import mathbreakers.unsubscribe
import mathbreakers.game
import mathbreakers.util

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    
    # Legacy and weird redirects
	url(r'^download/mac_home$', mathbreakers.views.simple_page('download.html')),
    url(r'^download/win_home$', mathbreakers.views.simple_page('download.html')),
    url(r'^download/linux_home$', mathbreakers.views.simple_page('download.html')),
    url(r'^download/mac_free$', mathbreakers.views.simple_page('download.html')),
    url(r'^download/win_free$', mathbreakers.views.simple_page('download.html')),
    url(r'^download/linux_free$', mathbreakers.views.simple_page('download.html')),
    url(r'^LASD/', mathbreakers.views.simple_page("lasd.html")),
    url(r'^session/try2/$', mathbreakers.session.teacher_try),
    url(r'^500/', "500"),


    # Simple pages
    url(r'^download/$', mathbreakers.views.simple_page('download.html')),
    url(r'^getmathbreakers/', mathbreakers.views.simple_page('buy_full.html')),
	url(r'^discussion/', mathbreakers.views.simple_page('discussion.html')),
    url(r'^privacy/$', mathbreakers.views.simple_page('privacy.html')),
    url(r'^tos/$', mathbreakers.views.simple_page('tos.html')),
    url(r'^contact/$', mathbreakers.views.simple_page('contact.html')),
    url(r'^learnmore/$', mathbreakers.views.simple_page('learnmore.html')),
    url(r'^sampledashboard/$', mathbreakers.views.simple_page('sampledashboard.html')),    
    url(r'^presskit/$', mathbreakers.views.simple_page('presskit.html')),
    url(r'^about/$', mathbreakers.views.simple_page('about.html')),
    url(r'^faq/$', mathbreakers.views.simple_page('faq.html')),
    url(r'^testimonials/$', mathbreakers.views.simple_page('testimonials.html')),
    url(r'^labs/$', mathbreakers.views.labs),
    url(r'^preorder/', mathbreakers.views.simple_page('buy_full.html')),
    url(r'^postpurchase/teacher/$', mathbreakers.views.simple_page('postpurchase_teacher.html')),
    url(r'^postpurchase/game/$', mathbreakers.views.simple_page('postpurchase_game.html')),
    url(r'^postpurchase/variable/$', mathbreakers.views.simple_page('postpurchase_variable.html')),
    url(r'^testimonials/', mathbreakers.views.simple_page('testimonials.html')),


    # Dynamic pages
    url(r'^$', mathbreakers.views.home),
    url(r'^logout/$', mathbreakers.views.logout),
    url(r'^notifyimage/$', mathbreakers.views.notify),
    url(r'^trial/$', mathbreakers.views.trial),
    url(r'^forgotpassword/$', mathbreakers.views.forgotpassword),
    url(r'^passwordreset/(.+)/$', mathbreakers.views.passwordreset),
    url(r'^download/full/(.+?)/$', mathbreakers.views.download_full),
    url(r'^HSBC/(.+?)/$', mathbreakers.views.hsbc),
    url(r'^HSBC/$', mathbreakers.views.hsbc),
    url(r'^code/(.+?)/$', mathbreakers.views.code),
    url(r'^code/$', mathbreakers.views.code), 
    url(r'^message/$', mathbreakers.views.message),
    url(r'^message_teacher/$', mathbreakers.views.message_teacher),
    url(r'^newsletter/$', mathbreakers.views.newsletter),    
    #url(r'^educents/(.+?)/$', mathbreakers.views.educents),
    url(r'^promotioncode/$', mathbreakers.views.educentspromotion),

    #webgl game
    url(r'^game/$', mathbreakers.game.game),
    url(r'^game/webgl_empty.html.mem', mathbreakers.util.make_redirect('/static/webgl/webgl_empty.html.mem')),
    url(r'^game/webgl_empty.data', mathbreakers.util.make_redirect('/static/webgl/webgl_empty.data')),

    url(r'^workertest/$', mathbreakers.views.simple_page("workertest.html")),

    # Logged in pages
    url(r'^settings/$', mathbreakers.userviews.settings),
    url(r'^settings/changepassword/$', mathbreakers.userviews.change_password),     

    # Ajax pages
    url(r'^ajax/signup/$', mathbreakers.ajax.signup),
    url(r'^ajax/signin/$', mathbreakers.ajax.signin),
    url(r'^ajax/createaccount/$', mathbreakers.ajax.createaccount),
    url(r'^ajax/download/([a-z]+)$', mathbreakers.ajax.download),
    url(r'^ajax/createteacheraccount/$', mathbreakers.ajax.createteacheraccount),
    url(r'^ajax/convertteacheraccount/$', mathbreakers.ajax.convertteacheraccount),
    url(r'^ajax/buttonlog/(.+?)/$', mathbreakers.ajax.buttonlog),

    # Pages used by mathbreakers game client
    url(r'^client/signin/$', mathbreakers.client.signin),
    url(r'^client/register/$', mathbreakers.client.register),
    url(r'^client/report/topics/$', mathbreakers.client.report_topics),
    url(r'^client/report/level/$', mathbreakers.client.report_level),

    url(r'^client/get/costume/$', mathbreakers.client.costume),
    url(r'^client/report/costume/$', mathbreakers.client.report_costume),

    url(r'^client/get/inventory/$', mathbreakers.client.inventory),
    url(r'^client/report/inventory/$', mathbreakers.client.report_inventory),

    url(r'^client/get/gems/$', mathbreakers.client.gems),
    url(r'^client/report/gems/$', mathbreakers.client.report_gems),

    url(r'^client/get/checkpoint/$', mathbreakers.client.checkpoint),
    url(r'^client/report/checkpoint/$', mathbreakers.client.report_checkpoint),

    ####### legacy items ########
    url(r'^client/inventory/$', mathbreakers.client.legacy_costume_gems_inventory),
    url(r'^client/report/items/$', mathbreakers.client.legacy_report_costume_gems_inventory),
    ####### sigh ################

    url(r'^client/refer/$', mathbreakers.client.refer_email),
    url(r'^client/gamestate/$', mathbreakers.client.gamestate),
    #url(r'^client/screenshot/$', mathbreakers.client.screenshot),
    url(r'^client/noticeimage/$', mathbreakers.client.notice_image),
    url(r'^client/assignments/$', mathbreakers.client.assignments),
    url(r'^client/report/heatmap/$', mathbreakers.client.heatmap),
    url(r'^client/report/menuclicks/$', mathbreakers.client.menuclicks),
    url(r'^client/roboterra/login/$', mathbreakers.client.roboterra_login),
    url(r'^client/skills/$', mathbreakers.client.skills),
    url(r'^client/report/skills/$', mathbreakers.client.report_skills),
    
    
    url(r'^client/version/(.+?)/$', mathbreakers.client.version),
    url(r'^client/message/(.+?)/$', mathbreakers.client.client_message),

    # Class sessions
    url(r'^session/client/nearby/$', mathbreakers.session.client_nearby),
    url(r'^session/client/names/$', mathbreakers.session.client_classroom_names),
    url(r'^session/client/login/$', mathbreakers.session.client_login),
    url(r'^session/client/register/$', mathbreakers.session.client_register),
    url(r'^session/classdetails/(.+?)/$', mathbreakers.session.classdetails),
    
    url(r'^session/try/$', mathbreakers.session.teacher_try),
    url(r'^session/start/$', mathbreakers.session.start),
    url(r'^session/later/$', mathbreakers.session.later),

    url(r'^session/ajax/users/$', mathbreakers.session.ajax_users),
    url(r'^session/ajax/playtime/$', mathbreakers.session.ajax_playtime),

    url(r'^session/selectclass/$', mathbreakers.session.selectclass),
    url(r'^session/status/$', mathbreakers.session.status),

    # Bugs
    url(r'^bugs/report/$', mathbreakers.bugs.report),

	# Database
	url(r'^modifydb/deleterow/$', mathbreakers.modifydb.deleterow),

    # Common Core 
    url(r'^cc/grade/$', mathbreakers.commoncore.grade),
    url(r'^cc/category/$', mathbreakers.commoncore.category),
    url(r'^cc/$', mathbreakers.commoncore.index),
    url(r'^cc/full/$', mathbreakers.commoncore.full),

    # Purchases
    url(r'^purchase/teacher/$', mathbreakers.purchase.teacher),
    url(r'^purchase/stripe/(.+)/$', mathbreakers.purchase.purchase_stripe),
    url(r'^pay/$', mathbreakers.purchase.pay_variable),

    url(r'^buy/$', mathbreakers.purchase.buy_full),

    # Classroom stuff
    url(r'^class/$', mathbreakers.classroom.manage),
    url(r'^class/dashboard/$', mathbreakers.classroom.dashboard),
    url(r'^class/ajax/remove/$', mathbreakers.classroom.ajax_remove),
    url(r'^class/ajax/assign/$', mathbreakers.classroom.ajax_assign),
    url(r'^class/ajax/unassign/$', mathbreakers.classroom.ajax_unassign),
    url(r'^class/ajax/getstudents/.*$', mathbreakers.classroom.ajax_getstudents),
    
	# SU
	url(r'^su/company_stats/$', mathbreakers.su.company_stats),
	url(r'^su/buttons/(.+?)/(.+?)$', mathbreakers.su.buttons_for),
	url(r'^su/buttons/(.+?)$', mathbreakers.su.buttons),
    url(r'^su/campsignups/$', mathbreakers.su.campsignups),
    url(r'^su/purchaseusers/$', mathbreakers.su.purchase_users),
    url(r'^su/userprogress/$', mathbreakers.su.user_progress),
	url(r'^su/preorder/$', mathbreakers.su.preorder),
	url(r'^su/generatefullgamecode/$', mathbreakers.su.generatefullgamecode),
	url(r'^su/teacher_emails/$', mathbreakers.su.list_teacher_emails),
	url(r'^su/classrooms/$', mathbreakers.su.classrooms),
    url(r'^su/makehugs/$', mathbreakers.su.makehugs),
    url(r'^su/getsurveys/$', mathbreakers.su.getsurveys),
    url(r'^su/teachersignupflow/$', mathbreakers.su.teacher_signup_flow),
    url(r'^su/partnerships/$', mathbreakers.su.partnerships),
    url(r'^su/userinfo/$', mathbreakers.su.userinfo),
    url(r'^su/loginas/(.+?)/$', mathbreakers.su.loginas),
    url(r'^su/teachers/$', mathbreakers.su.teachers),
	# url(r'^su/nc/$', mathbreakers.su.nc),
	url(r'^su/$', mathbreakers.su.index),
    url(r'^su/ajax/markteacher/$', mathbreakers.su.ajax_mark_teacher),
    url(r'^su/bugs/$', mathbreakers.bugs.show),

    # A/B cohorts
    url(r'^start/(.+?)/', mathbreakers.views.cohort_start),

	# analytics

mathbreakers/forms.py
from functools import partial

from django import forms
from django.utils.safestring import mark_safe
from django.contrib.auth.models import User
from django.forms import widgets
from django.utils.html import conditional_escape, format_html

from mathbreakers.models import *

GRADELEVELS = [
	("k", "Kindergarten"),
	("1", "First Grade"),
	("2", "Second Grade"),
	("3", "Third Grade"),
	("4", "Fourth Grade"),
	("5", "Fifth Grade"),
	("6", "Sixth Grade"),
	("7", "Seventh Grade"),
	("8", "Eighth Grade"),
	("multiple", "Multiple Grade Levels")]

class SignInForm(forms.Form):
	username = forms.CharField(max_length=100, required = True, label = "Username/Email")
	password = forms.CharField(max_length=100, widget=forms.PasswordInput, required = True, label = "Password")

class ChangePasswordForm(forms.Form):
	old_password = forms.CharField(max_length=100, widget=forms.PasswordInput, required=True, label="Old Password")
	new_password = forms.CharField(max_length=100, widget=forms.PasswordInput, required=True, label="New Password")
	new_password_repeat = forms.CharField(max_length=100, widget=forms.PasswordInput, required=True, label="Repeat New Password")

	def __init__(self, *args, **kwargs):
		self.request = kwargs.pop('request', None)
		super(ChangePasswordForm, self).__init__(*args, **kwargs)

	def clean(self):
		cleaned_data = super(ChangePasswordForm, self).clean()

		self.request.user.check_password(cleaned_data.get("oldpassword"))

		if cleaned_data.get("new_password") != cleaned_data.get("new_password_repeat"):
			self._errors["new_password_repeat"] = self.error_class(["You must enter the same password."])
		return cleaned_data

class AddClassroomForm(forms.Form):
	school = forms.CharField(min_length=4, max_length = 512, required = True, label="Name of your school*")
	classroom_name = forms.CharField(min_length=4, max_length=256, required=True, label="Name your classroom*")
	grade_level = forms.ChoiceField(GRADELEVELS)

class RedeemPreorderForm(forms.Form):
	why = forms.CharField(required=True, min_length=3, label="Why did you purchase Mathbreakers?")
	recommend = forms.CharField(required=True, min_length=1, label="Would you recommend Mathbreakers to a friend?")
	why_rec = forms.CharField(required=True, min_length=3, label="Why or why not?")
	comments = forms.CharField(required=False, label="Any comments or suggestions?")
	email = forms.EmailField(required = True, label="Email address*")

class ForgotPasswordForm(forms.Form):
	email = forms.EmailField()

class PasswordResetForm(forms.Form):
	new_password = forms.CharField(max_length=100, widget=forms.PasswordInput, required=True, label="New Password")
	new_password_repeat = forms.CharField(max_length=100, widget=forms.PasswordInput, required=True, label="Repeat New Password")

class StartLobbyForm(forms.Form):
	email = forms.EmailField(required=True, label="Enter your email address")
	password = forms.CharField(max_length=100, widget=forms.PasswordInput, required=True, label="Enter a password")
	classroom_name = forms.CharField(max_length=100, required=True, label="Name your classroom")

DateInput = partial(forms.DateInput, {'class': 'datepicker'})

class LobbyLaterForm(forms.Form):
	email = forms.EmailField(required=True)
	day = forms.DateField(widget=DateInput(), label="What day do you plan to use Mathbreakers?")

class WhichClassForm(forms.Form):
	which = forms.ChoiceField(label="Select a class")
	new_class = forms.CharField(max_length=100, required=False, label="Enter new class name")

	def __init__(self, user, *args, **kwargs):
		super(WhichClassForm, self).__init__(*args, **kwargs)
		choices = []
		choices.append((0, "+ New Classroom"))
		for ctr in ClassroomTeacherRel.objects.filter(user=user):
			choices.append((ctr.classroom.id,ctr.classroom.name))
		self.fields['which'].choices = choices

class TeacherPurchaseForm(forms.Form):
	num_students = forms.IntegerField(localize=False, required=True, initial="0", label="Approximately how many students will be playing?")

class HSBCForm(forms.Form):
	code = forms.CharField(max_length=100)

class CodeForm(forms.Form):
	code = forms.CharField(max_length=100)
	email = forms.EmailField(max_length=250)

class SUUserInfoForm(forms.Form):
	username = forms.CharField(max_length=256)

class EducentsCodeForm(forms.Form):
	email = forms.EmailField(required=True, label="Enter your email address")
	password = forms.CharField(max_length=100, widget=forms.PasswordInput, required=True, label="Enter a password")
	classroom_name = forms.CharField(max_length=100, required=True, label="Name your classroom")
	

mathbreakers/templates/teacher/accountcreationsuccess.html
{% extends "base.html" %}
{% load static %}

{% block styles %}
<link rel='stylesheet' href='{% static "css/session.css" %}' type='text/css'>
{% endblock %}

{% block scripts %}

{% endblock %}

{% block content %}
<div id="pagedescription">
	<h1>Success!</h1>
</div>
<div id="main">
	<h2>Yay!</h2>
	<a href="/session/status/">Continue classroom session</a>
</div>
{% endblock %}

mathbreakers/templates/teacher/addclass.html
{% extends "base.html" %}
{% load static %}

{% block styles %}
<link rel='stylesheet' href='{% static "css/addclass.css" %}' type='text/css'>
{% endblock %}

{% block content %}
<div id="pagedescription">
	<h1>Add a class</h1>
</div>
<div id="main">
	<form action="/class/add/" method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<input class="button blue" type="submit" value="submit"/>
	</form>
</div>
{% endblock %}

mathbreakers/templates/teacher/class_selection.html
	{% if classrooms|length > 1 %}
	<form id="class_selection_form" action="{{ request.path }}" method=GET>
		<select name="class_selection" id="class_selection">
			{% for cls in classrooms %}
			{% if classroom.name == cls.name %}
			<option value="{{ cls.name }}" selected>{{ cls.name }}</option>
			{% else %}
			<option value="{{ cls.name }}">{{ cls.name }}</option>
			{% endif %}
			{% endfor %}
		</select>
	</form>
	{% else %}
	<h1>{{ classroom.name }}</h1>
	{% endif %}
	<script>
		$(document).ready(function() {
			$("#class_selection").change(function() {
				$("#class_selection_form").submit();
			});
		});
	</script>

mathbreakers/templates/teacher/classbase.html
{% extends "base.html" %}
{% load static %}

{% block styles %}
<link rel='stylesheet' href='{% static "css/classbase.css" %}' type='text/css'>
{% endblock %}

{% block scripts %}
<script src='{% static "js/classbase.js" %}'></script>
{% endblock %}

{% block content %}
<div id="classbaseContainer">
	<div id="classNav">
		{% if classrooms|length > 1 %}
		<form id="class_selection_form" action="{{ request.path }}" method=GET>
			<label>Select Class</label>
			<select name="class_selection" id="class_selection">
				{% for cls in classrooms %}
				{% if classroom.name == cls.name %}
				<option value="{{ cls.id }}" selected>{{ cls.name }}</option>
				{% else %}
				<option value="{{ cls.id }}">{{ cls.name }}</option>
				{% endif %}
				{% endfor %}
			</select>
		</form>
		{% else %}
		<h1>{{ classroom.name }}</h1>
		{% endif %}
		<ul>
			<!-- <li><a id="instructions" href="/teacher/setup/1/">Instructions for Teachers</a></li>-->
			<li><a id="addclass" href="/session/status/">Lobby Page</a></li>
			<li><a id="dashboard" href="/class/dashboard/">My Dashboard</a></li>
			<li><a id="dashboard" href="/class/">Manage Class</a></li>
			<li><a id="addclass" href="/session/try/">Add new class</a></li>
			<li><a id="addclass" href="/faq/">FAQ</a></li>
		</ul>
	</div>
	<div id="classContent">
	{% block classTop %}
	{% endblock %}
	</div>
</div>	
{% block classMain %}
{% endblock %}
{% endblock %}

mathbreakers/templates/teacher/dashboard.html
{% extends "teacher/classbase.html" %}
{% load static %}

{% block styles %}
{{ block.super }}
<link rel='stylesheet' href='{% static "css/dashboard.css" %}' type='text/css'>
{% endblock %}

{% block scripts %}
{{ block.super }}
<script src='{% static "js/dashboard.js" %}'></script>
{% endblock %}

{% block classTop %}
<h1>Dashboard</h1>
<h2>See student progress and assign lessons</h2>
{% endblock %}

{% block classMain %}
<div id="main">
	{% if students|length > 0 %}
	<p style="font-size:16pt">
	Click on the grid to assign a lesson.
	</p>
	<div class="dashboard">
		<div id="assignmentLog"></div>
		<span class="group">
			<div style="display:block;visibility:hidden">.</div>
			<div class="studentsContainer">
				{% for student in students %}
				<div class="student">
					{{ student.first_name }}
				</div>
			{% endfor %}
			</div>
		</span>
		{% for group in groups %}
		{% if not group.owned %}
		<span class="group locked">
		{% else %}
		<span class="group">
		{% endif %}
			<h2>{{ group.name }}</h2>
			<div class="groupContainer">			
				{% for level in group.levels %}
				<div class="level">
					<h3>{{ level.short_name }}</h3>
					{% for entry in level.entries %}
					<div class="cell">
						<div 
						{% if not group.owned %}
						class="locked"
						{% endif %}
						{% if entry.type == "stars" %}
						class="icon {{ entry.data }}" 
						{% elif entry.type == "started" %}
						class="icon assignable started"
						{% else %}
						class="assignable"
						{% endif %}
						student = "{{ entry.student }}"
						student_name = "{{ entry.student_name }}"
						level = "{{ entry.level }}"
						{% if entry.assigned %}
						assigned=true
						{% endif %}
						>
							{% if entry.assigned %}
							<div class="assigned"></div>
							{% else %}
							<div class="unassigned"></div>
							{% endif %}						
						</div>
					</div>
					{% endfor %}
				</div>
				{% endfor %}
			</div>
			{% if not group.owned %}
			<div class="info">
				<a class="lockIcon" href="/lessons/{{group.lessonplan}}"></a>
			</div>
			{% endif %}
		</span>
		{% endfor %}
	</div>
	<div id="key">
		<div class="row"><div class="icon onestar"></div>Success - one star</div>
		<div class="row"><div class="icon twostar"></div> Success - two stars</div>
		<div class="row"><div class="icon threestar"></div> Success - three stars</div>
		<div class="row"><div class="icon started"></div> Started Playing </div>
		<div class="row"><div class="icon assigned"></div> Assigned</div>
	</div>	
	<p class="keydesc"></p>
	<div style="clear:both"></div>
	{% else %}
	<p>
		When students join your lobby, they will show up on this page so you can assign lessons etc. 
	</p>
	{% endif %}	
</div>
{% endblock %}

mathbreakers/templates/teacher/manageclass.html
{% extends "teacher/classbase.html" %}
{% load static %}

{% block styles %}
{{ block.super }}
<link rel='stylesheet' href='{% static "css/manageclass.css" %}' type='text/css'>
{% endblock %}

{% block scripts %}
{{ block.super }}
<script src='{% static "js/manageclass.js" %}'></script>
{% endblock %}

{% block classTop %}
<h1>Manage class</h1>
<h2>
	Add or remove students, or change their passwords. 
</h2>
{% endblock %}
{% block classMain %}
<div id="main">
<div id="ajaxing">...</div>	
<div id="nostudents">You have no students! When your students play Mathbreakers they can join your Lobby and they'll show up on this page.</div>	
<table><tbody></tbody></table>
</div>
{% endblock %}

mathbreakers/templates/teacher/nowform.html
{% extends "base.html" %}
{% load static %}

{% block styles %}
<link rel='stylesheet' href='{% static "css/session.css" %}' type='text/css'>
<link rel='stylesheet' href='{% static "css/nowform.css" %}' type='text/css'>
{% endblock %}

{% block scripts %}
{% endblock %}

{% block content %}
<div class="main">
	<div class="full-width-image" style="background-image:url('/static/img/screen_risers.jpg')">
		<h1>Start a Mathbreakers Lobby!</h1>
		<form id="nowform" method=POST action="/session/start/">
			{% csrf_token %}
			{{ start_form }}
			<input type="submit" id="startSession" class="button" value="Start!">
		</form>
	</div>
	<div id="moreinfo">
	You're just moments away from your first Mathbreakers session! Your students will appreciate the difference Mathbreakers offers, in our open and expansive video game world.
	<Br/><br/>
	Let math become your superpower!
	<br/><br/>
	</div>
</div>
{% endblock %}

mathbreakers/templates/teacher/sessionconvert.html
{% extends "base.html" %}
{% load static %}

{% block styles %}
<link rel='stylesheet' href='{% static "css/session.css" %}' type='text/css'>
{% endblock %}

{% block scripts %}

{% endblock %}

{% block content %}
<div id="pagedescription">
	<h1>Make an account!</h1>
	<h2>Track the progress of your students</h2>
</div>
<div id="main">
	<form action="/session/convert/" method=POST>
		{% csrf_token %}
		{{ form }}
		<input type="submit" class="button"/>
	</form>
</div>
{% endblock %}

mathbreakers/templates/teacher/teacher1.html
{% extends "teacher/teacherbase.html" %}
{% load static %}

{% block scripts %}
{{ block.super }}
<script src='{% static "js/teacher.js" %}'></script>
<script src='{% static "js/ajaxform.js" %}'></script>
{% endblock %}

{% block teacherstep %}	
	<div class="stepimg s1"></div>
	<div id="stepcontent">
		{% if user.is_authenticated %}
			{% if has_class %}
			<h2>Convert to teacher account</h2>
			<p>Great, you have a class!</p>
			{% else %}
			<h2>Convert to teacher account</h2>
			<p>Please fill out this brief form, and we'll convert your account to a teacher account with a fresh new empty classroom. Making a teacher account is <em>free</em> for a limited time!</p>
			<form id="teacherConvertForm">
		        {% csrf_token %}
		        {{ teacher_convert_form.as_p }}
		        <a id="teacherConvertSubmit" class="button blue" style="margin-left:30px" href="javascript:void(0)">Submit</a>
		    </form>
			{% endif %}
		{% else %}
		<h2>Make a teacher account</h2>
		<p>Please fill out this brief form, and we'll create a teacher account with a fresh new empty classroom just for you. Making a teacher account is <em>free</em> for a limited time!</p>
		<form id="teacherSignupForm">
	        {% csrf_token %}
	        {{ teacher_form.as_p }}
	        <a id="teacherSignupSubmit" class="button blue" style="margin-left:30px" href="javascript:void(0)">Submit</a>
	    </form>
	    {% endif %}
	</div>
	{% if user.is_authenticated and has_class %}	
	<a class="button blue" href="/teacher/setup/2/" style="margin:20px auto">Step 2</a>
	{% endif %}
{% endblock %}

mathbreakers/templates/teacher/teacher3.html
{% extends "teacher/teacherbase.html" %}
{% load static %}

{% block teacherstep %}	
	<div class="stepimg s3"></div>
	<div id="stepcontent">		
		<h2>Get the game</h2>
		<h3>You can now use Mathbreakers in the classroom!</h3>
		<div class="sectionsep">
			<p>
				Just download the game from <a href="/download/">mathbreakers.com/download</a> and have your students log in using the accounts you just created.
			</p>
			<img src="/static/img/howdownload.png" style="width:100%"/>
			<p>Having trouble running the game? See our <a href="/faq/">FAQ</a> for help troubleshooting.</p>
		</div>
		<div class="sectionsep">
			<p>	
				You will instantly have access to our lesson plans for a limited time, and you can track the progress of your students in your dashboard.
			</p>			
			<p>
				You can also use the dashboard to assign lessons to students. When they launch Mathbreakers on their computer they will be directed to the assigned lessons.
			</p>
				<a id="dashboard" href="/class/dashboard/" target="_blank" class="button blue" style="margin:20px auto">Dashboard</a>				
		</div>
		<div class="sectionsep">
			<p>
				You can always add students and access your dashboard from the navigation bar above.
			</p>
			<img src="/static/img/teachernav.png" style="margin:auto"/>
		</div>		
	</div>
{% endblock %}

mathbreakers/templates/teacher/whichclass.html
{% extends "base.html" %}
{% load static %}

{% block styles %}
<link rel='stylesheet' href='{% static "css/session.css" %}' type='text/css'>
{% endblock %}

{% block scripts %}
<script>
$(document).ready(function() {
	$("#id_which").change(function(e){
		var val = $("#id_which").val();
		console.log(val);
		if(val == 0) {
			$("#id_new_class").show();
			$("label[for='id_new_class']").show();
		} else {
			$("#id_new_class").hide();
			$("label[for='id_new_class']").hide();
		}
	});
});
</script>
{% endblock %}

{% block content %}
<div id="pagedescription">
	<h1>Select a Class</h1>
<h2>It looks like you already have a class.</h2>
<h2>Do you want to create a new one or use an existing one?</h2>
</div>
<div class="main">
	<form method=POST action="/session/selectclass/">
		{% csrf_token %}
		{{ form }}
		<input type="submit" id="picklobby" class="button" value="Start Lobby">
	</form>
</div>
{% endblock %}